name: Sync GitHub to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: Push to GitLab
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Add GitLab as a remote using your GitLab HTTPS URL and access token
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@git5.cs.fau.de/dpui/projects/coordinated-power-network-protection-based-on-machine-learning-techniques/pt-autoencoder.git

          # Push everything
          git push gitlab main:github-sync
